In [3]:
import os
import os.path as osp
import pandas as pd
import numpy as np
import torch

import torch_geometric.transforms as T
import shutil

from data import DailyData ,YearlyData
from transform import getfullstats,ScaleEdges


In [12]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [5]:
def get_edges(x,y):
    src = np.random.randint(0,x,3500)
    dest = np.random.randint(0,y, 3500)
    return [src,dest]

## Create graph structure

In [41]:
root = osp.join(os.getcwd(), "dailyroot")
dailydata = DailyData(root)

dailydata[0][("node2")].x[0]
dailydata[0][("node2", "to", "node1")].edge_attr[0]

edge_stats = getfullstats(dailydata)

Processing...
Done!


tensor([ 5., 19., 16., 10., 19., 15.])

tensor([ 4.,  2.,  8.,  3.,  7., 10.])

In [42]:
transform3 = T.Compose([ScaleEdges(stats=edge_stats), 
                        T.ToUndirected(), 
                        T.AddSelfLoops(),
                        T.NormalizeFeatures(attrs=["x", "edge_attr"])
                       ])

In [46]:
dailydata[0]

HeteroData(
  node1={
    x=[125, 6],
    num_nodes=125
  },
  node2={
    x=[200, 6],
    num_nodes=200
  },
  node3={
    x=[10, 6],
    num_nodes=10
  },
  (node2, to, node1)={
    edge_index=[2, 350],
    edge_attr=[350, 6],
    edge_label=[350, 1]
  },
  (node3, to, node2)={
    edge_index=[2, 350],
    edge_attr=[350, 5],
    edge_label=[350, 1]
  }
)

In [32]:
dailydata[0]

HeteroData(
  node1={
    x=[125, 6],
    num_nodes=125
  },
  node2={
    x=[200, 6],
    num_nodes=200
  },
  node3={
    x=[10, 6],
    num_nodes=10
  },
  (node2, to, node1)={
    edge_index=[2, 350],
    edge_attr=[350, 6],
    edge_label=[350, 1]
  },
  (node3, to, node2)={
    edge_index=[2, 350],
    edge_attr=[350, 5],
    edge_label=[350, 1]
  }
)

In [40]:
# Remove data and clear
del dailydata
shutil.rmtree(os.path.join(root,'processed'))

In [34]:
edge_stats

defaultdict(dict,
            {('node2',
              'to',
              'node1'): {'mean': tensor([[5.0456, 5.0205, 4.9991, 5.0307, 4.9823, 5.0022]]), 'std': tensor([[2.9074, 2.9172, 2.9090, 2.9441, 2.9231, 2.9069]]), 'min': tensor([0., 0., 0., 0., 0., 0.]), 'max': tensor([10., 10., 10., 10., 10., 10.])},
             ('node3',
              'to',
              'node2'): {'mean': tensor([[4.9630, 4.9994, 4.9730, 5.0233, 4.9690]]), 'std': tensor([[2.9068, 2.9189, 2.9122, 2.9012, 2.9194]]), 'min': tensor([0., 0., 0., 0., 0.]), 'max': tensor([10., 10., 10., 10., 10.])}})

In [35]:
# Larget data
root1 = osp.join(os.getcwd(), "dailyroot")
dailydata = DailyData(root1,transform =transform3)

Processing...
Done!


In [36]:
dailydata[0][("node2")].x[0]
dailydata[0][("node2", "to", "node1")].edge_attr[0]


tensor([0.2319, 0.0290, 0.1449, 0.1739, 0.1449, 0.2754])

tensor([0.0641, 0.0970, 0.0015, 0.2569, 0.2906, 0.2899])

In [27]:
dailydata[0]

HeteroData(
  node1={
    x=[125, 6],
    num_nodes=125
  },
  node2={
    x=[200, 6],
    num_nodes=200
  },
  node3={
    x=[10, 6],
    num_nodes=10
  },
  (node2, to, node1)={
    edge_index=[2, 350],
    edge_attr=[350, 6],
    edge_label=[350, 1]
  },
  (node3, to, node2)={
    edge_index=[2, 350],
    edge_attr=[350, 5],
    edge_label=[350, 1]
  },
  (node1, rev_to, node2)={
    edge_index=[2, 350],
    edge_attr=[350, 6],
    edge_label=[350, 1]
  },
  (node2, rev_to, node3)={
    edge_index=[2, 350],
    edge_attr=[350, 5],
    edge_label=[350, 1]
  }
)

In [38]:
dailydata[0][("node2")].x[0]
dailydata[0][("node2", "to", "node1")].edge_attr[0]
dailydata[0][("node1", "rev_to", "node2")].edge_attr[0]

tensor([0.2319, 0.0290, 0.1449, 0.1739, 0.1449, 0.2754])

tensor([0.0641, 0.0970, 0.0015, 0.2569, 0.2906, 0.2899])

tensor([0.0641, 0.0970, 0.0015, 0.2569, 0.2906, 0.2899])

In [39]:
ndata = dailydata[0]

HeteroData(
  node1={
    x=[125, 6],
    num_nodes=125
  },
  node2={
    x=[200, 6],
    num_nodes=200
  },
  node3={
    x=[10, 6],
    num_nodes=10
  },
  (node2, to, node1)={
    edge_index=[2, 350],
    edge_attr=[350, 6],
    edge_label=[350, 1]
  },
  (node3, to, node2)={
    edge_index=[2, 350],
    edge_attr=[350, 5],
    edge_label=[350, 1]
  },
  (node1, rev_to, node2)={
    edge_index=[2, 350],
    edge_attr=[350, 6],
    edge_label=[350, 1]
  },
  (node2, rev_to, node3)={
    edge_index=[2, 350],
    edge_attr=[350, 5],
    edge_label=[350, 1]
  }
)

In [111]:
x1 = ndata["node2"].x
x2 = ndata["node1"].x
src_edges = ndata[("node2", "to", "node1")].edge_index[:,:10][0].numpy().tolist()
dst_edges = ndata[("node2", "to", "node1")].edge_index[:,:10][1].numpy().tolist()

In [112]:
src_edges
dst_edges

[83, 33, 162, 17, 131, 185, 150, 101, 84, 153]

[1, 57, 23, 32, 19, 49, 23, 106, 65, 69]

In [117]:
def get_new_ids(src,dst):
    """
    Converting the fulldata index mapping into daily index
    This will require only a subset of nodes from the full files
    Based on that subset, the index mapping of each edge will change to suit it
    """
    # Gets the list of unique idx of src and dst from the given list of the file
    # Convert to tensort to run unique and sort, then convert to lsit for enumerate
    src_extract = torch.tensor(src).unique().numpy().tolist()
    dst_extract = torch.tensor(dst).unique().numpy().tolist()
    
    # Create a 0-n mapping for daily graph 
    new_src_ids = { k:i for i,k in enumerate(src_extract)}
    new_dst_ids = { k:i for i,k in enumerate(dst_extract)}
    
    # Get updated list of idx as it would be from day graphs nodes
    new_src = [new_src_ids[x] for x in src]
    new_dst = [new_dst_ids[x] for x in dst]
    
    # Create daily graph edge index
    edge_index = torch.tensor([new_src, new_dst])
    
    return edge_index, src_extract , dst_extract

In [119]:
edge_index, src_extract , dst_extract = get_new_ids(src_edges,dst_edges)
edge_index
src_extract
dst_extract
x1[src_extract]
x2[dst_extract]

tensor([[2, 1, 8, 0, 5, 9, 6, 4, 3, 7],
        [0, 5, 2, 3, 1, 4, 2, 8, 6, 7]])

[17, 33, 83, 84, 101, 131, 150, 153, 162, 185]

[1, 19, 23, 32, 49, 57, 65, 69, 106]

tensor([[0.0244, 0.3171, 0.2195, 0.1220, 0.1463, 0.1707],
        [0.2794, 0.1618, 0.0441, 0.2500, 0.0735, 0.1912],
        [0.0682, 0.4091, 0.0227, 0.2045, 0.1818, 0.1136],
        [0.2632, 0.1053, 0.0702, 0.2807, 0.2632, 0.0175],
        [0.0294, 0.2647, 0.1029, 0.1029, 0.2794, 0.2206],
        [0.4222, 0.0222, 0.0667, 0.0000, 0.1556, 0.3333],
        [0.2333, 0.1000, 0.2500, 0.1167, 0.1000, 0.2000],
        [0.3953, 0.0930, 0.0465, 0.0698, 0.3488, 0.0465],
        [0.3509, 0.1053, 0.1754, 0.0000, 0.1579, 0.2105],
        [0.1639, 0.2459, 0.0984, 0.1639, 0.0328, 0.2951]])

tensor([[0.1923, 0.1538, 0.0385, 0.1923, 0.3077, 0.1154],
        [0.2162, 0.2162, 0.0270, 0.2432, 0.1892, 0.1081],
        [0.0233, 0.2326, 0.2093, 0.1860, 0.2093, 0.1395],
        [0.1190, 0.1905, 0.1905, 0.1429, 0.1667, 0.1905],
        [0.0286, 0.2000, 0.0571, 0.2571, 0.2286, 0.2286],
        [0.1905, 0.0000, 0.1905, 0.0952, 0.4762, 0.0476],
        [0.1818, 0.2273, 0.2727, 0.0000, 0.2273, 0.0909],
        [0.4762, 0.0000, 0.0476, 0.1429, 0.2381, 0.0952],
        [0.0000, 0.0370, 0.3704, 0.1852, 0.2593, 0.1481]])

In [82]:
x[extract]

tensor([[0.0244, 0.3171, 0.2195, 0.1220, 0.1463, 0.1707],
        [0.2794, 0.1618, 0.0441, 0.2500, 0.0735, 0.1912],
        [0.0682, 0.4091, 0.0227, 0.2045, 0.1818, 0.1136],
        [0.2632, 0.1053, 0.0702, 0.2807, 0.2632, 0.0175],
        [0.0294, 0.2647, 0.1029, 0.1029, 0.2794, 0.2206],
        [0.4222, 0.0222, 0.0667, 0.0000, 0.1556, 0.3333],
        [0.2333, 0.1000, 0.2500, 0.1167, 0.1000, 0.2000],
        [0.3953, 0.0930, 0.0465, 0.0698, 0.3488, 0.0465],
        [0.3509, 0.1053, 0.1754, 0.0000, 0.1579, 0.2105],
        [0.1639, 0.2459, 0.0984, 0.1639, 0.0328, 0.2951]])

In [413]:
# with norm
edge
dailydata[0][edge].edge_attr

('node2', 'to', 'node1')

tensor([[0.2400, 0.1600, 0.0400, 0.2000, 0.2800, 0.0800],
        [0.1220, 0.1220, 0.1951, 0.0976, 0.2195, 0.2439],
        [0.2857, 0.1429, 0.0000, 0.1429, 0.1905, 0.2381],
        ...,
        [0.0606, 0.2727, 0.1212, 0.0909, 0.2727, 0.1818],
        [0.0667, 0.2667, 0.0333, 0.0333, 0.2667, 0.3333],
        [0.3478, 0.0435, 0.3478, 0.1304, 0.0435, 0.0870]])

In [425]:
edge
dailydata[0]

('node2', 'to', 'node1')

HeteroData(
  node1={
    x=[125, 6],
    num_nodes=125
  },
  node2={
    x=[200, 6],
    num_nodes=200
  },
  node3={
    x=[10, 6],
    num_nodes=10
  },
  (node2, to, node1)={
    edge_index=[2, 350],
    edge_attr=[350, 6],
    edge_label=[350, 1]
  },
  (node3, to, node2)={
    edge_index=[2, 350],
    edge_attr=[350, 5],
    edge_label=[350, 1]
  }
)

In [415]:
edge
dailydata[0][edge].edge_attr

('node2', 'to', 'node1')

tensor([[ 8.,  8.,  8.,  1.,  2.,  1.],
        [ 6., 10.,  3.,  7.,  8.,  2.],
        [ 7.,  5.,  2., 10.,  9.,  7.],
        ...,
        [ 1.,  3.,  3.,  9.,  8.,  7.],
        [10.,  9.,  5.,  8.,  8.,  8.],
        [ 7.,  5.,  9.,  7.,  3.,  7.]])

In [418]:
edge_stats

defaultdict(dict,
            {('node2',
              'to',
              'node1'): {'mean': tensor([[4.9704, 5.0217, 4.9824, 4.9783, 4.9735, 5.0510]]), 'std': tensor([[2.9055, 2.9068, 2.9248, 2.9173, 2.9218, 2.9098]]), 'min': tensor([0., 0., 0., 0., 0., 0.]), 'max': tensor([10., 10., 10., 10., 10., 10.])},
             ('node3',
              'to',
              'node2'): {'mean': tensor([[4.9957, 4.9654, 4.9852, 4.9712, 4.9738]]), 'std': tensor([[2.9001, 2.9188, 2.9030, 2.9044, 2.9073]]), 'min': tensor([0., 0., 0., 0., 0.]), 'max': tensor([10., 10., 10., 10., 10.])}})

In [416]:
xmean = edge_stats[edge]["mean"]
xstd = edge_stats[edge]["std"]
xmin,xmax = edge_stats[edge]["min"],edge_stats[edge]["max"]
x = dailydata[0][edge].edge_attr
   
(x-xmean)/(xmax-xmin)


tensor([[ 0.3030,  0.2978,  0.3018, -0.3978, -0.2974, -0.4051],
        [ 0.1030,  0.4978, -0.1982,  0.2022,  0.3026, -0.3051],
        [ 0.2030, -0.0022, -0.2982,  0.5022,  0.4026,  0.1949],
        ...,
        [-0.3970, -0.2022, -0.1982,  0.4022,  0.3026,  0.1949],
        [ 0.5030,  0.3978,  0.0018,  0.3022,  0.3026,  0.2949],
        [ 0.2030, -0.0022,  0.4018,  0.2022, -0.1974,  0.1949]])

In [255]:
#dataset = dailydata.shuffle()

In [390]:
from torch_geometric.loader import DataLoader
loader = DataLoader(dailydata, batch_size=4)
data = next(iter(loader))

In [400]:
data["node1"]

{'x': tensor([[0.1765, 0.1471, 0.1471, 0.0588, 0.2353, 0.2353],
        [0.0000, 0.0667, 0.2667, 0.3000, 0.2667, 0.1000],
        [0.3200, 0.2400, 0.3600, 0.0000, 0.0400, 0.0400],
        ...,
        [0.1714, 0.2286, 0.0286, 0.2857, 0.0571, 0.2286],
        [0.0909, 0.2121, 0.1515, 0.0606, 0.2727, 0.2121],
        [0.3214, 0.2143, 0.0000, 0.1786, 0.2143, 0.0714]]), 'num_nodes': 500, 'batch': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [393]:
data[("node2", "to", "node1")].edge_attr

tensor([[ 2.,  5.,  5.,  5.,  6.,  3.],
        [ 3.,  1.,  5.,  5.,  4., 10.],
        [ 4.,  4.,  8.,  3.,  3.,  4.],
        ...,
        [ 3.,  7.,  5.,  6.,  6.,  2.],
        [10.,  5.,  4.,  1.,  7., 10.],
        [ 1.,  3.,  7.,  9.,  5.,  8.]])

In [394]:
# InMemory data
root2 = osp.join(os.getcwd(), "yearlyroot")
yearlydata = YearlyData(root2)

In [395]:
yearlydata[0]

HeteroData(
  node1={
    x=[1250, 6],
    num_nodes=1250
  },
  node2={
    x=[2000, 6],
    num_nodes=2000
  },
  node3={
    x=[100, 6],
    num_nodes=100
  },
  (node2, to, node1)={
    edge_index=[2, 3500],
    edge_attr=[3500, 6],
    edge_label=[3500, 1]
  },
  (node3, to, node2)={
    edge_index=[2, 3500],
    edge_attr=[3500, 5],
    edge_label=[3500, 1]
  }
)

In [397]:
ydata = T.NormalizeFeatures()(yearlydata[0])

In [399]:
ydata["node1"]

{'x': tensor([[0.2051, 0.2308, 0.1026, 0.2308, 0.0513, 0.1795],
        [0.0286, 0.1714, 0.1714, 0.2286, 0.2571, 0.1429],
        [0.0312, 0.1875, 0.1875, 0.0625, 0.2812, 0.2500],
        ...,
        [0.2500, 0.1667, 0.1250, 0.0833, 0.0833, 0.2917],
        [0.0000, 0.0968, 0.2581, 0.2258, 0.1613, 0.2581],
        [0.2353, 0.2353, 0.0882, 0.1471, 0.1176, 0.1765]]), 'num_nodes': 1250}

## Loading - Daily

In [8]:
n = (len(dailydata) + 9) // 10
train_dataset = dailydata[:2*n]
val_dataset = dailydata[2*n:2*n+n]
train_dataset = dailydata[2*n+n:]

In [9]:
train_dataset

DailyData(21)

In [370]:
data = T.ToUndirected()(dailydata)
data = T.AddSelfLoops()(data)
data = T.NormalizeFeatures()(data)

AttributeError: 'DailyData' object has no attribute 'edge_stores'

In [15]:
from torch_geometric.loader import DataLoader
loader = DataLoader(train_dataset, batch_size=5)

In [16]:
len(loader)

5

In [17]:
sampled_hetero_data = next(iter(loader))
sampled_hetero_data

HeteroDataBatch(
  node1={
    x=[625, 6],
    num_nodes=625,
    batch=[625],
    ptr=[6]
  },
  node2={
    x=[1000, 6],
    num_nodes=1000,
    batch=[1000],
    ptr=[6]
  },
  node3={
    x=[50, 6],
    num_nodes=50,
    batch=[50],
    ptr=[6]
  },
  (node2, to, node1)={
    edge_index=[2, 1750],
    edge_attr=[1750, 6],
    edge_label=[1750, 1]
  },
  (node3, to, node2)={
    edge_index=[2, 1750],
    edge_attr=[1750, 5],
    edge_label=[1750, 1]
  }
)

In [18]:
sampled_hetero_data[("node2", "to", "node1")].edge_index

tensor([[ 35, 181,  78,  ..., 840, 817, 873],
        [ 82, 112,  11,  ..., 617, 503, 508]])

### Transforms

In [378]:
loader = DataLoader(dailydata, batch_size=len(dailydata))
data = next(iter(loader))

In [ ]:
transform = T.Compose([T.ToUndirected(), T.AddSelfLoops()])
data = transform(data)
data

In [382]:
data = T.NormalizeFeatures()(dailydata)

AttributeError: 'DailyData' object has no attribute 'stores'

In [375]:
# Get full data stats for normalization
import torch_geometric.transforms as T
from collections import defaultdict
from copy import copy

def getfullstats(dailydata):
    """
    Pass the data into a loader to get the full stats
    Do this before Transforms that add reverse edges 
    Create a transform for this if you want to limit edge columns
    """
    loader = DataLoader(dailydata, batch_size=len(dailydata))
    data = next(iter(loader))
    edge_stats = defaultdict(dict)
    for edge in data.edge_types: 
        e = data[edge].edge_attr
        # get stats
        edge_stats[edge]["mean"] = e.mean(dim=0, keepdim=True)
        edge_stats[edge]["std"] = e.std(dim=0, keepdim=True)
        edge_stats[edge]["min"] = torch.min(e, 0).values
        edge_stats[edge]["max"] = torch.max(e, 0).values
    return edge_stats    

def edge_norm_fn(edge_stats):
    """
    Normalization of edge_attributes
    """
    for edge in data[0].edge_types:
        norm_data = copy(data)
        xmean = edge_stats[edge]["mean"]
        xstd = edge_stats[edge]["std"]
        xmin,xmax = edge_stats[edge]["min"],edge_stats[edge]["max"]
        for i in range(len(data)): 
            x = norm_data[i][edge].edge_attr
            del data[i][edge].edge_attr
            norm_data[i][edge].edge_attr = (x-xmean)/(xmax-xmin)
    return norm_data


edge_stats = getfullstats(dailydata)

In [377]:
new_data = edge_norm_fn(dailydata)
data[3][dailydata[0].edge_types[1]].edge_attr
new_data[3][dailydata[0].edge_types[1]].edge_attr

tensor([[ 5.,  3.,  6.,  7.,  1.],
        [ 9.,  8.,  0.,  8.,  4.],
        [ 2.,  5.,  7., 10.,  1.],
        ...,
        [10.,  7.,  7.,  3.,  5.],
        [ 2.,  2.,  9.,  7.,  1.],
        [ 3.,  8.,  3.,  8.,  7.]])

tensor([[ 5.,  3.,  6.,  7.,  1.],
        [ 9.,  8.,  0.,  8.,  4.],
        [ 2.,  5.,  7., 10.,  1.],
        ...,
        [10.,  7.,  7.,  3.,  5.],
        [ 2.,  2.,  9.,  7.,  1.],
        [ 3.,  8.,  3.,  8.,  7.]])

In [342]:
data = dailydata[0]
edge = dailydata[0].edge_types[0]
x = data[edge].edge_attr
xmean = edge_stats[edge]["mean"]
xmin,xmax = edge_stats[edge]["min"],edge_stats[edge]["max"]

x
data[edge].edge_attr = (x-xmean)/(xmax-xmin)
data[edge].edge_attr

tensor([[ 8.,  4.,  9.,  5.,  5.,  3.],
        [ 4.,  1.,  2.,  8.,  7.,  8.],
        [ 7.,  7.,  4.,  7.,  8.,  5.],
        ...,
        [ 1.,  4.,  1.,  2.,  9.,  5.],
        [ 8.,  2.,  5.,  8., 10.,  7.],
        [ 9.,  8.,  1.,  1.,  8.,  2.]])

tensor([[ 0.3030, -0.1022,  0.4018,  0.0022,  0.0026, -0.2051],
        [-0.0970, -0.4022, -0.2982,  0.3022,  0.2026,  0.2949],
        [ 0.2030,  0.1978, -0.0982,  0.2022,  0.3026, -0.0051],
        ...,
        [-0.3970, -0.1022, -0.3982, -0.2978,  0.4026, -0.0051],
        [ 0.3030, -0.3022,  0.0018,  0.3022,  0.5026,  0.1949],
        [ 0.4030,  0.2978, -0.3982, -0.3978,  0.3026, -0.3051]])

In [345]:
dailydata[0][edge].edge_attr

tensor([[ 8.,  4.,  9.,  5.,  5.,  3.],
        [ 4.,  1.,  2.,  8.,  7.,  8.],
        [ 7.,  7.,  4.,  7.,  8.,  5.],
        ...,
        [ 1.,  4.,  1.,  2.,  9.,  5.],
        [ 8.,  2.,  5.,  8., 10.,  7.],
        [ 9.,  8.,  1.,  1.,  8.,  2.]])

In [ ]:
data[i][edge].edge_attr = (x-xmean)/(xmax-xmin)

In [335]:
transform(dailydata[0])

In [336]:
data_t[0][("node2", "to", "node1")].edge_attr

tensor([[ 8.,  4.,  9.,  5.,  5.,  3.],
        [ 4.,  1.,  2.,  8.,  7.,  8.],
        [ 7.,  7.,  4.,  7.,  8.,  5.],
        ...,
        [ 1.,  4.,  1.,  2.,  9.,  5.],
        [ 8.,  2.,  5.,  8., 10.,  7.],
        [ 9.,  8.,  1.,  1.,  8.,  2.]])

In [ ]:
def transform_fn(data):
   data[edge_type].edge_attr
   return data

## File index mapping

In [21]:
node1x = torch.rand((350,4))
node2x = torch.rand((1000,7))
node3x = torch.rand((60,4))

In [ ]:
idx1 = torch.tensor(self.get_edges(200, 125), dtype=torch.long)

In [20]:
nodex

tensor([[0.4921, 0.3575, 0.4293, 0.7944],
        [0.7774, 0.0929, 0.7056, 0.0589],
        [0.7587, 0.2424, 0.5981, 0.3171],
        ...,
        [0.1629, 0.4417, 0.3113, 0.8817],
        [0.4475, 0.1902, 0.1020, 0.9192],
        [0.6733, 0.2430, 0.9555, 0.1451]])

In [ ]:
# test Data split and creation

## Changes

In [ ]:
def train(model, optimizer, train_loader, device):
    model.train()

    for data in train_loader:
        optimizer.zero_grad()
        data = data.to(device)
        out = model(data.pos, data.batch)
        loss = F.nll_loss(out, data.y)
        loss.backward()
        optimizer.step()



val_losses, accs, durations = [], [], []

if torch.cuda.is_available():
        torch.cuda.synchronize()
    t_start = time.perf_counter()

for epoch in range(epochs):
    train_loss = train(model, optimizer, train_loader)
    val_losses.append(eval_loss(model, val_loader))
    accs.append(eval_acc(model, test_loader))
    eval_info = {
        'fold': fold,
        'epoch': epoch,
        'train_loss': train_loss,
        'val_loss': val_losses[-1],
        'test_acc': accs[-1],
    }
    
if torch.cuda.is_available():
    torch.cuda.synchronize()
t_end = time.perf_counter()
durations.append(t_end - t_start)

print(f'Epoch: {epoch:03d}, Test: {test_acc:.4f}, '
              f'Duration: {t_end - t_start:.2f}')

